#pragma once

#define GSDK_ENVIRONMENT_CLIENT (1 << 0)
#define GSDK_ENVIRONMENT_SERVER (1 << 1)
#define GSDK_ENVIRONMENT_HYBRID (GSDK_ENVIRONMENT_CLIENT|GSDK_ENVIRONMENT_SERVER)

#ifndef GSDK_ENVIRONMENT
	#error
#endif

#if !(GSDK_ENVIRONMENT & GSDK_ENVIRONMENT_SERVER)
	#error
#endif

#define GSDK_ENGINE_TF2     0
#define GSDK_ENGINE_PORTAL2 1
#define GSDK_ENGINE_L4D2    2

#ifndef GSDK_ENGINE
	#error
#endif

#define GSDK_ENGINE_BRANCH_2007 0
#define GSDK_ENGINE_BRANCH_2010 1

#define GSDK_ENGINE_BRANCH_2007_V0 0
#define GSDK_ENGINE_BRANCH_2007_V1 1
#define GSDK_ENGINE_BRANCH_2007_V2 2

#define GSDK_ENGINE_BRANCH_2010_V0 0
#define GSDK_ENGINE_BRANCH_2010_V1 1

#if GSDK_ENGINE == GSDK_ENGINE_TF2
	#define GSDK_ENGINE_BRANCH         GSDK_ENGINE_BRANCH_2007
	#define GSDK_ENGINE_BRANCH_VERSION GSDK_ENGINE_BRANCH_2007_V2
#elif GSDK_ENGINE == GSDK_ENGINE_L4D2
	#define GSDK_ENGINE_BRANCH         GSDK_ENGINE_BRANCH_2010
	#define GSDK_ENGINE_BRANCH_VERSION GSDK_ENGINE_BRANCH_2010_V0
#elif GSDK_ENGINE == GSDK_ENGINE_PORTAL2
	#define GSDK_ENGINE_BRANCH         GSDK_ENGINE_BRANCH_2010
	#define GSDK_ENGINE_BRANCH_VERSION GSDK_ENGINE_BRANCH_2010_V1
#else
	#error
#endif

#define GSDK_CHECK_BRANCH_VER(branch, op, ver) (GSDK_ENGINE_BRANCH == branch && GSDK_ENGINE_BRANCH_VERSION op ver)

#if GSDK_ENGINE == GSDK_ENGINE_PORTAL2
	#define GSDK_NO_SYMBOLS
#endif

#if GSDK_ENGINE != GSDK_ENGINE_TF2 && defined __x86_64__
	#error
#endif
